### ISSUE TITLE
Data Loading for Benchmarking

### ISSUE THREAD

**Issue by fredmontet** [ontime-re/ontime#33]
## Goal

Develop a common way to load data for benchmarking purposes

## Description

One of the issue with benchmarking is the difference in dataset structure. Within the onTime benchmarking module, this problem aims at being solved in three different aspects. First, with the availability of common datasets in the library. Second, with helper methods to create custom datasets and use them alongside any other 'onTime compatible' ones. Third, by following the already existing dataset structure 'TimeEval' as suggested by Jonathan.

### Tasks

- [x] Check if something could be used from TimeEval[1]
- [x] Check the TimeEval data format[1].
- [x] Create a directory called `data` in https://github.com/fredmontet/ontime/tree/develop/src/ontime/module to make this new module
- [x] Add some basic datasets, see if those in Darts could be used.
- [x] Develop helper methods to add custom datasets
- [x] Make an example of how to use the developed method in a notebook

## Reference 

[1] https://timeeval.readthedocs.io/en/latest/

**Comment by JunodCharlie** [comment]
**Check if something could be used from TimeEval**
TimeEval has a file converter script that could be useful. but it's meant to be used on the command line so it'd need to be adapted to fit into ontime.

The benchmarking part itself looks interesting as well though the doc in this part is still a WIP.

**Check the TimeEval data format**
The file format is basically a comma separated CSV with headers and an index column (integers or timestamps) [doc link](https://timeeval.readthedocs.io/en/latest/concepts/datasets.html#canonical-file-format)

**Comment by fredmontet** [comment]
Since the issue #41 was created, this one can be closed.
