### ISSUE TITLE
Benchmarking module fix for zero and full-shot learning scenarios

### ISSUE THREAD

**Issue by fredmontet** [ontime-re/ontime#48]
# Tasks

- [x] Load a checkpoint
- [x] Zero shot scenario
- [x] Predictions retrieving for plotting
- [x] Full shot scenario
- [x] Documentation of the implemented feature
