### ISSUE TITLE
Add models

### ISSUE THREAD

**Issue by fredmontet** [ontime-re/ontime#9]
## Description

Currently, the addition of models requires a small wrapper. Since many models are available on time series libraries, the idea of this issue is to develop a feature to leverage all those models without the need to make a wrapper around all off them. This means that onTime would be mostly 'model free' but interoperable with others.

## Tasks

- [x] Make a concept allowing interoperability of Darts and GluonTS
- [x] Make a notebook that demonstrates the usage
- [x] #17
- [ ] #18
- [ ] #19
- [ ] GluonTS
- [ ] Kats
- [ ] See if another lib could be added

## Refs
https://github.com/MaxBenChrist/awesome_time_series_in_python

**Comment by fredmontet** [comment]
Inclusion of GluonTS and Kats caused some dependencies issues, I decided to add SkForecast instead for now. Now, all Darts and Scikit-learn API compatible models can be used.
